version: "2"
run:
  build-tags:
    - e2e
linters:
  exclusions:
    presets:
      - std-error-handling
    paths:
      - zz_generated.*\.go$
  settings:
    staticcheck:
        checks:
        - all # default
        - '-ST1000' # default       
        - '-ST1003' # default
        - '-ST1016' # default
        - '-ST1020' # default
        - '-ST1021' # default
        - '-ST1022' # default
        - '-ST1001' # ST1001: should not use dot imports
        - '-ST1005' # ST1005: error strings should not be capitalized
formatters:
  enable:
    - gci
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/aws/eks-hybrid)
      custom-order: true
    gofumpt:
      extra-rules: true
  exclusions:
    paths:
      - zz_generated.*\.go$

