version: 0.2

phases:
  build:
    commands:
    - make build-cross-platform e2e-tests-binary e2e-setup

cache:
  paths:
    - '/root/.cache/go-build/**/*'
    - '/go/pkg/mod/**/*'

artifacts:
  files:
  - "_bin/**/*"
  - "_bin/e2e.test"
  - "_bin/e2e-test-runner"
  - "buildspecs/*"
  - "testdata/nodeconfig.yaml"
