version: 0.2

phases:
  build:
    commands:
    - make build-cross-platform e2e-tests-binary e2e-setup ginkgo

cache:
  paths:
    - '/root/.cache/go-build/**/*'
    - '/go/pkg/mod/**/*'

artifacts:
  files:
  - "_bin/**/*"
  - "buildspecs/*"
  - "hack/run-e2e.sh"
