version: 0.2

phases:
  build:
    commands:
    - ./hack/build-nodeadm.sh $GIT_VERSION

cache:
  paths:
    - '/root/.cache/go-build/**/*'
    - '/go/pkg/mod/**/*'

artifacts:
  files:
  - "_bin/**/*"
  - "buildspecs/*"
  - "hack/*"
  - "test/e2e/cni/testdata/**/*"  
