version: 0.2

phases:
  build:
    commands:
    - ./hack/upload-dev-release-artifacts.sh $ARTIFACTS_BUCKET

  post_build:
    commands:
    - ./hack/validate-release-artifacts.sh $ARTIFACTS_BUCKET latest
