version: 0.2

phases:
  pre_build:
    commands:
      # ensure staging release artifacts are valid before starting prod release
      - ./hack/validate-release-artifacts.sh $STAGING_BUCKET latest
      - echo "Downloading artifacts from staging bucket..."
      - aws s3 sync --no-progress s3://${STAGING_BUCKET}/latest/ ./latest
      - export VERSION=$(cat latest/GIT_VERSION)
      - echo "Using version:"
      - cat latest/GIT_VERSION

      - echo "Setting up AWS config for role assumption..."
      - |
        cat << EOF > awscliconfig
        [profile artifacts-production]
        role_arn=${PROD_ARTIFACT_DEPLOYMENT_ROLE}
        region=us-east-1
        credential_source=EcsContainer
        EOF
      - export AWS_CONFIG_FILE=$(pwd)/awscliconfig
      - aws configure list-profiles

  build:
    commands:
      - AWS_PROFILE=artifacts-production ./hack/release-nodeadm.sh "${PROD_BUCKET}" "${VERSION}"

  post_build:
    commands:
      - AWS_PROFILE=artifacts-production ./hack/validate-release-artifacts.sh $PROD_BUCKET releases/${VERSION}
      - AWS_PROFILE=artifacts-production ./hack/validate-release-artifacts.sh $PROD_BUCKET releases/latest
      - AWS_PROFILE=artifacts-production ./hack/validate-release.sh "${CLOUDFRONT_DISTRIBUTION_ID}" "latest/GIT_VERSION"
