name: build-and-unit-test
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
    paths:
      - '**'
permissions:
  contents: read
  pull-requests: read
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"
          check-latest: true
          cache: true
      - name: build application
        run: make build-cross-platform
  test:
    name: unit-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"
          check-latest: true
          cache: true
      - name: build application
        run: make test
