name: build-e2e-test-binaries
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
    paths:
      - '**'
permissions:
  contents: read
  pull-requests: read
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21"
          check-latest: true
          cache: true
      - name: build e2e test binaries
        run: make e2e-tests-binary e2e-test
