name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
    paths:
      - '**'
permissions:
  contents: read
  pull-requests: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          check-latest: true
          cache: true
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1.6
          # Disable package caching to avoid a double cache with setup-go.
          skip-pkg-cache: true
          args: --timeout 10m
