name: integration-test
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
    paths:
      - '**'
permissions:
  contents: read
  pull-requests: read
jobs:
  test:
    name: integration-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21"
          check-latest: true
          cache: true
      - name: integration test
        run: make test-integration