name: "Vulnerability scan"
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
    paths-ignore:
    - 'buildspecs/**'
    - 'crds/**'
    - 'docs/**'
    - 'example/**'
    - 'hack/**'
    - 'hybrid-nodes-cdk/**'
    - 'scripts/**'
    - 'testdata/**'
  workflow_dispatch:
  schedule:
    # every day at 7am UTC
    - cron: '0 7 * * *'
permissions:
  contents: read
jobs:
  govulncheck:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
        with:
          show-progress: false
      - name: govulncheck
        uses: golang/govulncheck-action@v1
        with:
          check-latest: true
          repo-checkout: false
          go-version-file: go.mod
